sudo: required

services:
  - docker
  
language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  
before_install:
  - ./test/setup-testenv.sh

install:
  - npm install -g mocha
  - npm install

script:
  - npm run test-and-coverage && cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage && rm -rf ./coverage
